name: Continuous-Integration-Pipeline(CI)
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest test_app.py --html=report.html
        
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: arn:aws:iam::822469302283:role/zumo-test-oidc-role
          aws-region: eu-west-1

      - name: Upload HTML report to S3
        run: aws s3 cp report.html s3://zumo-test-reports/report.html

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::822469302283:role/zumo-test-oidc-role
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get the short SHA
        id: sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Build Tag and push Docker image
        env:
          ECR_REGISTRY: 822469302283.dkr.ecr.eu-west-1.amazonaws.com/zumo-test-registry
        run: |
          IMAGE_TAG=${{ steps.sha.outputs.sha }}
          docker build -t $ECR_REGISTRY:$IMAGE_TAG .
          docker push $ECR_REGISTRY:$IMAGE_TAG
      
      - name: Syncing  static content to S3
        run: |
          aws s3 sync ./static s3://zumo-eks-cdn/static
          aws s3 cp ./templates/index.html s3://zumo-eks-cdn/templates/index.html

      - name: Invalidating CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E14RWBGE2ZIKLZ --paths "/templates/index.html"
      


      - name: Updating new image tag in values.yaml file
        env:
          ECR_REGISTRY: 822469302283.dkr.ecr.eu-west-1.amazonaws.com/zumo-test-registry
        run: |
          IMAGE_TAG=${{ steps.sha.outputs.sha }}
          sed -i 's|repository: .*$|repository: '"$ECR_REGISTRY"'|' zumo-test/values.yaml
          sed -i 's|tag: .*$|tag: '"$IMAGE_TAG"'|' zumo-test/values.yaml


      - name: Setting Git Config
        run: |
          git config --local user.email "captain.gab@protonmail.com"
          git config --local user.name "GH-runner"
        
      - name: Stage Changes
        run: git add zumo-test/values.yaml
        
      - name: Commit Changes
        run: git diff-index --quiet HEAD || git commit -m "Update image repository and tag to $ECR_REGISTRY:${{ steps.sha.outputs.sha }}"
        
      - name: Push Changes
        run: git push origin HEAD:main