# Default values for zumo-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 15

image:
  repository: 822469302283.dkr.ecr.eu-west-1.amazonaws.com/zumo-test-registry
  tag: 1da21e5
  pullPolicy: Always


service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
 

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"

    
autoscaling:
  enabled: false
  minReplicas: 4
  maxReplicas: 12
  targetCPUUtilizationPercentage: 80

strategy:
  type: RollingUpdate
  maxUnavailable: 1
  maxSurge: 4

container:
  name: zumo-test
  port: 8080