apiVersion: v1
kind: Service
metadata:
  name: {{ include "zumo-test.fullname" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    {{- include "zumo-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "zumo-test.selectorLabels" . | nindent 4 }}
